---
  # Site.yml to manage the Ansible-ContainerDeploys Playbook.

  - name: ensure docker.io is installed and running
    roles:
      - docker.install

  - name: deploy containers
    roles:
      - container.deploy
