---
  # Site.yml to manage the Ansible-ContainerDeploys Playbook.

  - name: ensure docker.io is installed and running
    roles:
      - docker.install

  - name: launch nginx webserver
    roles:
      - nginx.deploy
    tags:
      - nginx
