---
# tasks file for roles/container.deploy

  - name: launch nginx container
    docker:
      name: "{{ container_name }}"
      image: "{{ container_image }}"
      pull: always
      state: reloaded
      restart_policy: always
      ports: "{{ ansible_default_ipv4.address }}:{{ internal_docker_port }}:{{ external_server_port }}"
