---
# tasks file for container.deploy

  - name: launch nginx container
    docker:
      name: basenginx
      image: quay.io/e30chris/basenginx
      pull: always
      state: reloaded
      restart_policy: always
      ports: "{{ ansible_default_ipv4.address }}:80:80"
